session: diss

root: ~/src/dissertation-project

windows:
  - name: build-shell

  - name: python-shell
    commands:
      - source .venv/bin/activate
      - ./ns3 shell

  - name: editor
    commands:
      - nvim
